all: intro

intro: 
	@echo "¡Importante que lea el manual de usuario antes de ejecutar la aplicación!"
	@echo "Para ejecutar el servidor escriba 'make serv'"
	@echo "Para ejecutar el cliente escriba  'make cli'"
	@echo "Para ejecutar los test escriba  'make test'"
	
serv:
	@echo "Se ejecuta el servidor:"
	python3 Servidor.py 

cli:
	@echo "Se ejecuta el cliente:"
	python3 Cliente.py

test: 
	@echo "Se ejecutan los test:"
	python3 Test.py